name: スクレイピングとデプロイ

on:
  schedule:
    - cron: "*/3 0-11 * * *"  # UTCで0時から11時（日本時間9時から20時）まで3分ごとに実行
  workflow_dispatch:  # 手動実行用
    inputs:
      duration:
        description: '実行継続時間（分）'
        required: true
        default: '180'
        type: choice
        options:
          - '30'
          - '60'
          - '120'
          - '180'
          - '360'

env:
  # 環境変数を明示的に設定
  BASE_URL: 'https://apollo-scedure77.net'
  LOGIN_URL: 'https://apollo-scedure77.net/LOGIN/'
  USERNAME: 'imurayap33'
  PASSWORD: 'imimp0633'

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: master  # masterブランチを明示的に指定

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Chrome と ChromeDriver のインストール
        uses: nanasess/setup-chromedriver@v2

      - name: logsディレクトリを作成
        run: mkdir -p logs

      - name: 必要なパッケージをインストール
        run: pip install -r requirements.txt

      - name: 手動実行の場合は指定時間繰り返し実行
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "手動実行モード: ${{ github.event.inputs.duration }}分間、3分ごとに実行します"
          start_time=$(date +%s)
          end_time=$((start_time + ${{ github.event.inputs.duration }} * 60))
          current_time=$(date +%s)
          
          while [ $current_time -lt $end_time ]; do
            echo "スクレイピング実行: $(date)"
            python mail_time_check.py
            
            echo "変更をコミット"
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add -A
            git diff --quiet && git diff --staged --quiet || git commit -m "スクレイピング結果を更新: $(date +%Y-%m-%d_%H:%M:%S)" && git push
            
            echo "3分間スリープ"
            sleep 180
            current_time=$(date +%s)
          done

      - name: スケジュール実行の場合は1回だけ実行
        if: github.event_name == 'schedule'
        run: python mail_time_check.py
        timeout-minutes: 15  # タイムアウト設定

      - name: スケジュール実行時の変更をコミット
        if: github.event_name == 'schedule'
        run: |
          echo "スクリプト実行完了時間: $(date)" >> execution_log.txt
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "スクレイピング結果を更新: $(date +%Y-%m-%d_%H:%M:%S)"
          git push

  deploy:
    needs: scrape
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3
        with:
          ref: master  # mainからmasterに変更
      
      - name: Netlifyにデプロイ
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: "./"
          production-branch: "master"  # mainからmasterに変更
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "GitHub Actionsからの自動デプロイ: $(date +%Y-%m-%d_%H:%M:%S)"
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} 