name: スクレイピングとデプロイ

on:
  schedule:
    - cron: "*/10 21-23,0-11 * * *"  # 日本時間9:00-20:00に対応（UTCで21-23時、0-11時）、10分ごとに実行
  workflow_dispatch:  # 手動実行用
    inputs:
      mode:
        description: '実行モード'
        required: true
        default: 'single'
        type: choice
        options:
          - 'single'  # 1回だけ実行
          - 'repeat'  # 繰り返し実行
      duration:
        description: '繰り返し実行の継続時間（分）- repeatモードのみ有効'
        required: true
        default: '180'
        type: choice
        options:
          - '30'
          - '60'
          - '120'
          - '180'
          - '360'

env:
  # 環境変数を明示的に設定
  BASE_URL: 'https://apollo-scedure77.net'
  LOGIN_URL: 'https://apollo-scedure77.net/LOGIN/'
  USERNAME: 'imurayap33'
  PASSWORD: 'imimp0633'
  TZ: 'Asia/Tokyo'  # タイムゾーンを日本時間に設定

jobs:
  scrape_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: master  # masterブランチを明示的に指定

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Chrome と ChromeDriver のインストール
        uses: nanasess/setup-chromedriver@v2

      - name: logsディレクトリを作成
        run: mkdir -p logs

      - name: 必要なパッケージをインストール
        run: pip install -r requirements.txt

      - name: Netlify CLI をインストール
        run: npm install -g netlify-cli
        
      - name: 手動実行（1回のみ）の場合
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.mode == 'single'
        run: |
          echo "手動実行モード（1回のみ）: $(date '+%Y-%m-%d %H:%M:%S JST')"
          
          # スクレイピングを実行
          python mail_time_check.py
          
          # 変更をコミット
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "スクレイピング結果を更新: $(date '+%Y-%m-%d %H:%M:%S JST')" && git push
          
          # Netlifyにデプロイ
          echo "Netlifyにデプロイします: $(date '+%Y-%m-%d %H:%M:%S JST')"
          npx netlify deploy --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }} --message "単発実行からのデプロイ: $(date '+%Y-%m-%d %H:%M:%S JST')"

      - name: 手動実行（繰り返し）の場合
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.mode == 'repeat'
        run: |
          echo "手動実行モード（繰り返し）: ${{ github.event.inputs.duration }}分間、10分ごとに実行します"
          echo "現在の日本時間: $(date '+%Y-%m-%d %H:%M:%S')"
          start_time=$(date +%s)
          end_time=$((start_time + ${{ github.event.inputs.duration }} * 60))
          current_time=$(date +%s)
          
          # 初回の実行
          while [ $current_time -lt $end_time ]; do
            # スクレイピングを実行
            echo "スクレイピング実行: $(date '+%Y-%m-%d %H:%M:%S')"
            python mail_time_check.py
            
            # 変更をコミット
            echo "GitHub に変更をコミット"
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add -A
            git diff --quiet && git diff --staged --quiet || git commit -m "スクレイピング結果を更新: $(date '+%Y-%m-%d %H:%M:%S JST')" && git push
            
            # Netlifyにデプロイ
            echo "Netlifyにデプロイします: $(date '+%Y-%m-%d %H:%M:%S JST')"
            npx netlify deploy --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }} --message "繰り返し実行からのデプロイ: $(date '+%Y-%m-%d %H:%M:%S JST')"
            
            # 次の実行までスリープ（残り時間が10分未満の場合はスリープしない）
            remaining_time=$((end_time - $(date +%s)))
            if [ $remaining_time -gt 600 ]; then
              echo "10分間スリープ"
              sleep 600
            else
              echo "残り時間が10分未満のため、終了します"
              break
            fi
            
            current_time=$(date +%s)
          done

      - name: スケジュール実行の場合
        if: github.event_name == 'schedule'
        run: |
          echo "スケジュール実行: 現在の日本時間: $(date '+%Y-%m-%d %H:%M:%S')"
          
          # スクレイピングを実行
          python mail_time_check.py
          
          # 変更をコミット
          echo "スクリプト実行完了時間: $(date '+%Y-%m-%d %H:%M:%S JST')" >> execution_log.txt
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "スクレイピング結果を更新: $(date '+%Y-%m-%d %H:%M:%S JST')" && git push
          
          # Netlifyにデプロイ
          echo "Netlifyにデプロイします: $(date '+%Y-%m-%d %H:%M:%S JST')"
          npx netlify deploy --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }} --message "スケジュール実行からのデプロイ: $(date '+%Y-%m-%d %H:%M:%S JST')"
        timeout-minutes: 15  # タイムアウト設定 